spring.application.name=academic-scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/scheduler
spring.datasource.username=scheduler
spring.datasource.password=scheduler

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
